"""Add document blob

Revision ID: 843d4d16f208
Revises: 0584f7f19142
Create Date: 2026-06-03 18:23:46.093607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '843d4d16f208'
down_revision: Union[str, None] = '0584f7f19142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_blobs',
    sa.Column('blob_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('blob_name')
    )
    op.create_index(op.f('ix_document_blobs_blob_name'), 'document_blobs', ['blob_name'], unique=False)
    op.create_index(op.f('ix_document_blobs_user_id'), 'document_blobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_blobs_user_id'), table_name='document_blobs')
    op.drop_index(op.f('ix_document_blobs_blob_name'), table_name='document_blobs')
    op.drop_table('document_blobs')
    # ### end Alembic commands ###
